# Generated by Django 5.2.4 on 2025-08-03 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=265, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=265, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=265, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='The username "me" is not allowed.', regex="^(?!me$).*"
                    ),
                    django.core.validators.RegexValidator(
                        message="Use Valid symbols for username.",
                        regex="^[\\w.@+-]+\\Z",
                    ),
                ],
                verbose_name="User Name",
            ),
        ),
    ]
